spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portsight
    username: postgres
    password: Sathish@1969
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:Jz7BExPDCTChI1xZ5uvT50zXhc+rDYeRbrnzCUP2WjA=}
  expiration-ms: 86400000

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html